from datetime import datetime
import warnings

from models.watermark_faster import watermark_model
from options import get_parser_main_model

# Ignore warnings
warnings.filterwarnings('ignore')


def watermark_embed_demo(raw):
    watermarked_text = model.embed(raw)
    return watermarked_text


def watermark_extract(raw):
    is_watermark, p_value, n, ones, z_value = model.watermark_detector_fast(raw)
    confidence = (1 - p_value) * 100
    return f"{confidence:.2f}%"


def precise_watermark_detect(raw):
    is_watermark, p_value, n, ones, z_value = model.watermark_detector_precise(raw)
    confidence = (1 - p_value) * 100
    return f"{confidence:.2f}%"


def watermarking_test():
    # init
    print("init...")
    ti0 = datetime.now()
    print("nltk")
    import nltk
    nltk.download('punkt')
    print("model")
    model = watermark_model(language='English', mode='embed', tau_word=0.8, lamda=0.83)
    ti = datetime.now()
    print("init done.")

    # watermark
    ori_text = 'Call me Ishmael. Some years ago—never mind how long precisely—having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world. It is a way I have of driving off the spleen and regulating the circulation. Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me, that it requires a strong moral principle to prevent me from deliberately stepping into the street, and methodically knocking people’s hats off—then, I account it high time to get to sea as soon as I can. This is my substitute for pistol and ball. With a philosophical flourish Cato throws himself upon his sword; I quietly take to the ship. There is nothing surprising in this. If they but knew it, almost all men in their degree, some time or other, cherish very nearly the same feelings towards the ocean with me.'

    print("watermarking...")
    tw0 = datetime.now()
    wm_text = (model.embed(ori_text)
               .replace(' .', '.')
               .replace(' ,', ',')
               .replace(' ;', ',')
               .replace(' \' s ' , '\'s ')
               .replace(' \'', '\'')
               )
    tw = datetime.now()
    print(wm_text)

    print()

    print(f'init took {ti - ti0}s, wm took {tw - tw0}s')


if __name__ == "__main__":
    watermarking_test()
    exit(0)

    opts = get_parser_main_model().parse_args()
    model = watermark_model(language=opts.language, mode=opts.mode, tau_word=opts.tau_word, lamda=opts.lamda)

    while True:
        print("\n" + "=" * 66)
        print("Watermarking Text Generated by Black-Box Language Models".center(60))
        print("Created by Xi Yang (yx9726@mail.ustc.edu.cn)".center(60))
        print("=" * 60 + "\n")

        print("1. Inject Watermark")
        print("2. Detect Watermark")
        print("3. Exit\n")

        choice = input("Enter your choice (1/2/3): ")

        if choice == '1':
            print("\n" + "-" * 60)
            text = input("Enter the text to embed a watermark: ")
            watermarked_text = watermark_embed_demo(text)
            print("\n" + "-" * 60)
            print(f"Watermarked Text:\n{watermarked_text}")
            print("-" * 60)

        elif choice == '2':
            print("\n" + "-" * 60)
            text = input("Enter the text to analyze: ")
            mode = input("Select detection mode (Fast/Precise): ")

            if mode.lower() == 'fast':
                confidence = watermark_extract(text)
            elif mode.lower() == 'precise':
                confidence = precise_watermark_detect(text)
            else:
                print("Invalid mode. Please choose 'Fast' or 'Precise'.")
                continue

            print("\n" + "-" * 60)
            print(f"Confidence (the likelihood of the text containing a watermark): {confidence}")
            print("-" * 60)

        elif choice == '3':
            print("\nExiting...")
            break

        else:
            print("Invalid choice. Please choose 1, 2, or 3.")
